apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-hello-world
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-hello-world
    app.kubernetes.io/part-of: test-app-mjrv
  name: devfile-sample-hello-world
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: devfile-sample-hello-world
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: devfile-sample-hello-world
    spec:
      containers:
      - image: quay.io/susdas_quay_org/build-e2e-gevu-tenant/test-app-mjrv/devfile-sample-hello-world@sha256:344e5a18a742410af89cdae20661b55870c4877517d4ff5a3aef24b4cddb5185
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
